### PR TITLE
deps: Vendor dependencies via dep(1)

### PR DESCRIPTION
**Pull request by jen20**
This pull request records and vendors the dependencies for wirelatency using Go's `dep` tool.

cc @sean-

### CODE REVIEW

**Comment by jen20** [comment]
Fixes #9.

**Comment by redhotpenguin** [comment]
Hi James,

I pulled in `Gopkg.lock` and `Gopkg.toml` into a test instance via `dep ensure` on Ubuntu / Gcloud, and verified that the pinned packages build and work successfully. I think we're good to go on the versions, but could you remove the actual source from the commit? We don't generally add the vendored repos to master, just the dependency lists.

**Comment by redhotpenguin** [comment]
Thanks for the great contribution - we will be implementing this, but slightly differently than in this PR. I discussed this at length with @maier again, we weighed the pros and cons of a few approaches, and came up with the following approach that we will be applying to all circonus-labs golang projects.

- We will vendor dependencies in, as pulled in via `dep ensure` with the shas locked as currently done.
- To prevent the possibility of inadvertent vendoring in possibly malicious code (see [go-bindata situation](https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/)), updates to vendored code will only be implemented by circonus-labs members, so that we are tasked with this responsibility.
- If an update to a vendored library is needed, a github issue will need to be opened with the relevant library and version info (Gopkg stanza would be perfect).

So to implement this process for these dependencies, I am going to:

1. `dep ensure` and commit these dependencies
2. Open up a new PR
3. Close out this PR
4. Document this process and apply to other -labs golang project

Thanks again for helping drive what we think is a good solution here. Hat tip to @sean- also.

**Comment by redhotpenguin** [comment]
Closing - effort implemented in #13 via documented process above. Thanks folks!

**Pull request closed without merging**
